name:   树酱のYellow picture Bot

on:
  schedule:
     - cron: '0 * * * *'  # 原本是6分钟，回头改回去
  workflow_dispatch:  # 支持手动触发

jobs:
  run-trading-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # 限制最大运行时间
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy python-okx

      - name: Run trading bot
        env:
          OKX_API_KEY: ${{ secrets.OKX_API_KEY }}
          OKX_API_SECRET: ${{ secrets.OKX_API_SECRET }}
          OKX_PASSPHRASE: ${{ secrets.OKX_PASSPHRASE }}
        run: |
          python Github-OKX-CQbtc.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trading-logs
          path: trading_bot.log


